name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate Pacman SVG
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: simoabid

      - name: Push generated files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add .
          git commit -m "Generate contribution graph" || exit 0
          git push
